//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlyOfficeControl.Controls.OnlyOfficeEditorBundle
{
    public partial class OnlyOfficeEditor
    {
        protected global::System.Web.UI.WebControls.HiddenField hfEditedDocumentBase64;
    }
}
