//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Los cambios en este archivo podrían causar un comportamiento incorrecto
//     y se perderán si se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlyOfficeControl.Controls
{
    public partial class OnlyOfficeEditor
    {
        /// <summary>
        /// HiddenField que almacena el documento editado en base64
        /// tras invocar captureToHiddenField() desde JavaScript.
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField hfEditedDocumentBase64;
    }
}
